### ISSUE TITLE
Webhook message not sent (Error 400: BAD REQUEST)

### ISSUE THREAD

**Issue by Davoleo** [DiscordHooks/travis-ci-discord-webhook#16]
Reference: https://github.com/DiscordHooks/travis-ci-discord-webhook/issues/6

Log & Buildscript file: https://gist.github.com/Davoleo/64deb682643e41cb50bbb11e2079a450

**Comment by Davoleo** [comment]
This happens just when the build ends with failure

**Comment by D4RKAR117** [comment]
This type of errors can happen, when the discord server or one of its channels have webhooks administration disabled. The request of the server revots because it does not validate because discord can not accept this request for the webhook in specific.

It can also be home from which gradlew in its compilation cirra sockets of depuration that creates travis. but this is not 100% confirmed.

**Comment by k3rn31p4nic** [comment]
> This type of errors can happen, when the discord server or one of its channels have webhooks administration disabled.

Nope. The **Bad Request** error is returned by Discord because the webhook data is malformed. This is the reason I requested a verbose output from the OP.

**Comment by D4RKAR117** [comment]
Only administrators per server, can disable for specific channels the administration of webhooks
On the other hand, what you say has a little more meaning and I never thought about it, but I always solve the error in that way

**Comment by Davoleo** [comment]
Answering @D4RKAR117  the fact is that when the build ends succesfully it sends the message, then if the webhook is able to send message in one case I can't think why it wouldn't in the other case

@k3rn31p4nic I'll try that link as soon as possible

**Comment by Davoleo** [comment]
ok so, got a new failed build using the verbose version
here's the failed build log you were looking for @k3rn31p4nic 
https://travis-ci.org/Davoleo/Metallurgy-4-Reforged/builds/458543424

**Comment by k3rn31p4nic** [comment]
@Davoleo Can you run that build again? I've updated the script to show the webhook data, which will show why it's giving a bad request error.

**Comment by Davoleo** [comment]
now it does work again :/ 
![image](https://user-images.githubusercontent.com/24458276/49345671-4d707180-f688-11e8-86a5-eeea662d6c97.png)

here's the broken build link though: https://travis-ci.org/Davoleo/Metallurgy-4-Reforged/builds/462568035

**Comment by k3rn31p4nic** [comment]
This build log won't help. I would require a build log of a build that failed but the webhook wasn't sent successfully. I'm keeping this issue open until then.

**Comment by Ellypse** [comment]
Hi. I have the same issue but with builds that are actually succeeding. Here's the build with the verbose script https://travis-ci.org/Ellypse/Total-RP-3/builds/480591420

**Comment by k3rn31p4nic** [comment]
@Ellypse Looking at your webhook data, the description field contains two unescaped `"` characters (as highlighted in the screenshot below). That looks like the main reason for the failure. Can you try after changing that?
That's your commit user name, you can change that using the `git config user.name` command.
![image](https://user-images.githubusercontent.com/19631364/51320614-49da5380-1a58-11e9-8b02-ba5b5a8c3f3f.png)

**Comment by Ellypse** [comment]
Thanks for the answer. I have always been using this username and it never caused any issue with other tools. A contributor pushed something on the same repo after me and it worked, and they don't have special characters in their name, so I guess this is indeed the issue.

I will change it on my end, but I guess you might want to escape it on your side too at some point? Since Travis is testing my pull request I guess some bad things could happen if someone is submitting a PR on my project and put some clever stuff between `"` in their username.

**Comment by k3rn31p4nic** [comment]
I just wanted to make sure that this was the issue. It is indeed an issue on our side, and this script should escape it to prevent this kinda errors. Thanks!

**Comment by Ellypse** [comment]
I can confirm removing the `"` in the user name has fixed my issue and the webhooks are working correctly now. Thanks 🙂

**Comment by Davoleo** [comment]
so huh, rn it seems to be working fine with failed builds so I'll close this ticket, I'll comment again in case it breaks again, thanks for all the support!

**Comment by Davoleo** [comment]
I've managed to reproduce that bug again 
here's the failed build verbose log https://travis-ci.com/Davoleo/Metallurgy-4-Reforged/builds/114022119

**Comment by k3rn31p4nic** [comment]
I'm not seeing any character in the webhook data that can lead to a bad request 🤔 
Can you try to rebuild and see if you're still getting bad request error?

**Comment by Davoleo** [comment]
I've tried restarting the build but, no luck :P 
https://travis-ci.com/Davoleo/Metallurgy-4-Reforged/builds/114022119#L855

**Comment by k3rn31p4nic** [comment]
Strange, because I'm not seeing any issues in the webhook data.
Is this happening just for that specific build, or for some other builds too?

**Comment by Davoleo** [comment]
by now it's the only failed build that failed to send the webhook too, but yeah it happens rarely
furthermore failed builds are not very common either

**Comment by k3rn31p4nic** [comment]
Well, in that case I'll keep this issue open for now. If any other webhook fails, please link them here so I can compare.

**Comment by mateuszdrwal** [comment]
im having the same issue, json seems valid though according to a validator. logs below since its a private repo. it worked about a day ago when i first set it up, but it broke down overnight with seemingly no reason at all. any attempts to send it now end with 400, also tested running it manually from a debug build.

```
[Webhook]: Sending webhook to Discord...

START WEBHOOK_DATA
{
  "username": "",
  "avatar_url": "https://travis-ci.org/images/logos/TravisCI-Mascot-1.png",
  "embeds": [ {
    "color": 3066993,
    "author": {
      "name": "Job #18.1 (Build #18) Passed - mateuszdrwal/xxx",
      "url": "https://travis-ci.com/mateuszdrwal/xxx/builds/118148064",
      "icon_url": "https://travis-ci.org/images/logos/TravisCI-Mascot-blue.png"
    },
    "title": "  Testing if userPreferences in openstego require icon    new file:   challenges/forensics/Deep_Shit/LICENSE      new file:   ch
allenges/forensics/Deep_Shit/openstego.ico      modified:   challenges/forensics/Deep_Shit/solve.py",
    "url": "",
    "description": "\n\nmarwenn02 authored & committed",
    "fields": [
      {
        "name": "Commit",
        "value": "[`f65ce60`](https://github.com/mateuszdrwal/xxx/commit/xxx)",
        "inline": true
      },
      {
        "name": "Branch/Tag",
        "value": "[`master`](https://github.com/mateuszdrwal/xxx/tree/master)",
        "inline": true
      }
    ],
    "timestamp": "2019-07-06T18:41:31Z"
  } ]
}
END WEBHOOK_DATA
*   Trying 162.159.129.233...
* Connected to discordapp.com (162.159.129.233) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 594 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_ECDSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: ssl711320.cloudflaressl.com (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: EC
*        certificate version: #3
*        subject: OU=Domain Control Validated,OU=PositiveSSL Multi-Domain,CN=ssl711320.cloudflaressl.com
*        start date: Thu, 28 Mar 2019 00:00:00 GMT
*        expire date: Fri, 04 Oct 2019 23:59:59 GMT
*        issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO ECC Domain Validation Secure Server CA 2
*        compression: NULL
* ALPN, server accepted to use http/1.1
> POST /api/webhooks/xxx/xxx HTTP/1.1
> Host: discordapp.com
> User-Agent: TravisCI-Webhook
> Accept: */*
> Content-Type:application/json
> X-Author:k3rn31p4nic#8383
> Content-Length: 1125
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
* The requested URL returned error: 400 BAD REQUEST
* Closing connection 0
curl: (22) The requested URL returned error: 400 BAD REQUEST

[Webhook]: Unable to send webhook.
```

**Comment by mateuszdrwal** [comment]
i restarted a build from yesterday which did send the webhook and it worked again. here is the log of the working webhook ```[Webhook]: Sending webhook to Discord...

START WEBHOOK_DATA
{
  "username": "",
  "avatar_url": "https://travis-ci.org/images/logos/TravisCI-Mascot-1.png",
  "embeds": [ {
    "color": 15158332,
    "author": {                                                                                                                        [36/65]
      "name": "Job #7.1 (Build #7) Failed - mateuszdrwal/xxx",
      "url": "https://travis-ci.com/mateuszdrwal/xxx/builds/118141786",
      "icon_url": "https://travis-ci.org/images/logos/TravisCI-Mascot-red.png"
    },
    "title": "trying to fix travis #6",
    "url": "",
    "description": "\n\nmateuszdrwal authored & committed",
    "fields": [
      {
        "name": "Commit",
        "value": "[`97280dc`](https://github.com/mateuszdrwal/xxx/commit/xxx)",
        "inline": true
      },
      {
        "name": "Branch/Tag",
        "value": "[`master`](https://github.com/mateuszdrwal/xxx/tree/master)",
        "inline": true
      }
    ],
    "timestamp": "2019-07-06T19:49:54Z"
  } ]
}
END WEBHOOK_DATA
*   Trying 162.159.129.233...
* Connected to discordapp.com (162.159.129.233) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 594 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_ECDSA_AES_128_GCM_SHA256
*        server certificate verification OK
*        server certificate status verification SKIPPED
*        common name: ssl711320.cloudflaressl.com (matched)
*        server certificate expiration date OK
*        server certificate activation date OK
*        certificate public key: EC
*        certificate version: #3
*        subject: OU=Domain Control Validated,OU=PositiveSSL Multi-Domain,CN=ssl711320.cloudflaressl.com
*        start date: Thu, 28 Mar 2019 00:00:00 GMT
*        expire date: Fri, 04 Oct 2019 23:59:59 GMT
*        issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO ECC Domain Validation Secure Server CA 2
*        compression: NULL
* ALPN, server accepted to use http/1.1
> POST /api/webhooks/xxx/xxx HTTP/1.1
> Host: discordapp.com
> User-Agent: TravisCI-Webhook
> Accept: */*
> Content-Type:application/json
> X-Author:k3rn31p4nic#8383
> Content-Length: 933
> 
* upload completely sent off: 933 out of 933 bytes
< HTTP/1.1 204 NO CONTENT
< Date: Sat, 06 Jul 2019 19:49:55 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Set-Cookie: __cfduid=dc3db2c24514bad33ba97c1c27a4dadb61562442595; expires=Sun, 05-Jul-20 19:49:55 GMT; path=/; domain=.discordapp.com; HttpOnly
< Strict-Transport-Security: max-age=31536000; includeSubDomains
< X-RateLimit-Bucket: 3cd1f278bd0ecaf11e0d2391374c011d
< X-RateLimit-Limit: 5
< X-RateLimit-Remaining: 4
< X-RateLimit-Reset: 1562442598
< Via: 1.1 google
< Alt-Svc: clear
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Server: cloudflare
< CF-RAY: 4f241acb9a9e55c2-ORD
< 
* Connection #0 to host discordapp.com left intact

[Webhook]: Successfully sent the webhook.```

**Comment by k3rn31p4nic** [comment]
@mateuszdrwal Your failing webhook has a newline character in the `title`:
```json
    "title": "  Testing if userPreferences in openstego require icon    new file:   challenges/forensics/Deep_Shit/LICENSE      new file:   ch
allenges/forensics/Deep_Shit/openstego.ico      modified:   challenges/forensics/Deep_Shit/solve.py",
```
that can be the reason Discord is returning bad request error.

**Comment by mateuszdrwal** [comment]
that seems to be one issue with that specific case, though probably caused by poorly copying the output from the terminal. for some reason, webhooks for builds on my commits are getting sent fine but not webhooks on my friends commits. i just tried it with another build, and while travis failed to send the webhook i copied the json data into postman to try and send it manually and it just worked. this leads me to believe the issue has something to do with how the json is being sent in the send.sh script

**Comment by k3rn31p4nic** [comment]
Can you show the build log for the commit you just mentioned?

**Comment by mateuszdrwal** [comment]
better yet, i found the underlying issue: on the failing webhooks the value of the title key starts with a tab character. somewhere along the way between printing the WEBHOOK_DATA and pasting it into postman it is converted into a space, which discord can handle. it doesnt seem to handle titles starting with tabs though and returns the following error when the webhook is send with curl, or when the space is replaced with a tab manually in postman: ```json
{
    "code": 50006,
    "message": "Cannot send an empty message"
}

after discovering this, i checked @Davoleo's logs and the issue there seems to be that the description field contains tab characters. discord webhooks seem to have a general allergy to tabs. im submitting a pull request in a minute.
```

**Comment by pinkcutearrow** [comment]
I have this same issue and I am new to GitHub. I have made an issue but no one has helped. Can I get some help???

**Comment by k3rn31p4nic** [comment]
@pinkcutearrow And a 400 error means that there is some error with the request itself. I'll look into your issue but where have you made the issue? I'm not seeing any opened issue from you. Can you give your issue number?

**Comment by mateuszdrwal** [comment]
looks like this is it https://github.com/pinkcutearrow/pinkcutearrow/issues/1

**Comment by k3rn31p4nic** [comment]
:man_facepalming:

**Comment by aderchox** [comment]
I'm having the same issue. I'm simply adding a server's webhook to the webhooks of a Github repository for receiving the notification of the pushs, (I've also added a "/github" at the end of the generated URL as the Discord manual says is highly required) but still Github is giving a Bad Request error. (the red alert triangle near the name of the webhook saying the last try was not successful).
