### ISSUE TITLE
Notifications sent twice in the discord channel

### ISSUE THREAD

**Issue by axelvaindal** [DiscordHooks/travis-ci-discord-webhook#18]
Hi guys, great work for this ! 

I've been using your script to send webhook notifications to my discord server when travis complete the build, but weirdly enough, it seems the notifications are sent twice.
Moreoever, the build numbers do not match the one I got on my travis dashboard.

Here is a screenshot of the notifications received : 

![image](https://user-images.githubusercontent.com/11026659/52337092-fe87e500-2a06-11e9-9d6e-7908bc9844f6.png)

And here is the screenshot of the travis related dashboard : 

![image](https://user-images.githubusercontent.com/11026659/52337137-1d867700-2a07-11e9-928c-a848996965aa.png)

Are you aware of this and if yes, do you know how to fix this ?

**Comment by k3rn31p4nic** [comment]
Click on the embed title and it'll redirect you to the build for which the notification was sent. And see if they redirect correctly or not.

**Comment by axelvaindal** [comment]
Weirdly enough, it seems one notification is from travis-ci.org and another is from travis-ci.com, do you know anything about that ?

**Comment by k3rn31p4nic** [comment]
You've probably set it to run in two different places.

**Comment by axelvaindal** [comment]
I'm only using what you proposed in your README.md : 

```
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
```

However, it does seem like travis-ci.org was the old DNS used by the travis team to build public repository, and it will be removed someday to only use travis-ci.com.
Due to this, any push done to a public repository with travis configuration on seems to be pushed both on travis-ci.com and travis-ci.org , thus the script being executed twice.
Do you have any public repository running travis on which you can confirm this behavior ?

**Comment by k3rn31p4nic** [comment]
No, that's not what it is. I've my builds running on `.org` and that's not causing this issue. You've probably connected your repository both in `.org` and `.com`. You need to disconnect/remove it from one of them.
