### ISSUE TITLE
[suggestion] Custom message for errored builds

### ISSUE THREAD

**Issue by Davoleo** [DiscordHooks/travis-ci-discord-webhook#19]
I don't know if this is doable, but it would be awesome if the hook could send a red/gray status message for errored builds instead of not sending anything

**Comment by k3rn31p4nic** [comment]
This is not possible because when a build stops because of error due to Travis itself, it instantly stops. THere's no way in that condition to send a webhook from there. So, I'm closing this issue. Thanks!

**Comment by Davoleo** [comment]
ok, thanks for the answer!
I wonder how jenkins notifier does it then 🤔
