### ISSUE TITLE
Discord Gaming Community Webhook

### ISSUE THREAD

**Issue by BenThePeasant** [DiscordHooks/travis-ci-discord-webhook#33]
I was trying to send a webhook to my server and it had a check mark next to the box but it never sent.
![image](https://user-images.githubusercontent.com/73324373/96958313-09c8c000-14cb-11eb-8455-18ed44d4b81f.png)

**Comment by k3rn31p4nic** [comment]
You're in the wrong place. This repo is from Travis CI to Discord webhook, not for GitHub to Discord webhook.
