### ISSUE TITLE
Multiple Discord Hook Support

### ISSUE THREAD

**Issue by D4RKAR117** [DiscordHooks/travis-ci-discord-webhook#8]
Hi i want to request support to multiple discord hooks, its awesome and its so great how this works, maybe a recursive WEBHOOK_URL Env Variable recognition or array?

Keep the good work 👍

**Comment by D4RKAR117** [comment]
i think, set a env variable with an hook array or something else, and the script will only recognize this and set up into the script

**Comment by k3rn31p4nic** [comment]
Opening this up for [Hacktoberfest](https://hacktoberfest.digitalocean.com) if anyone wants to contribute.
